### ISSUE TITLE
Catalog: добавить обёртки в фильтре

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/barbershop-id85318#1]
Оберни в блоке `aside` > `form` чекбоксы  с заголовком в свой блок, и радиобаттоны сос воим заголовком в другой. Можешь для наглядности использовать `legend`, а можешь `div`, особой разницы нет.

**Comment by stan-devproject** [comment]
Ок, я взял их в fieldset + вместо h2 поставил legend.

Вопрос по теме:  Как мне прикреплять подписи label к input`ам в данном случае?

Вариант #1:

```
<input type="radio" name="filter-group" id="filter-g1" value="1" checked>
<label for="filter-g1" class="filter-groups">Бритвенные принадлежности</label>
```

Вариант #2:

```
<label class="filter-groups">
  <input type="radio" name="filter-group" id="filter-g1" value="1" checked>
  Бритвенные принадлежности
</label>
```

По идеи, оба же варианта допустимы?

**Comment by elemeNtk0** [comment]
Сорян. Я спутал фиелдсет с легендой. Заголовок верни в `h2`. А фиелдсеты оставь)
стилизовать будет проще.

Подписи оставь как вариант 1. А еще лучше добавь обёртку для каждой пары

``` html
<div>
  <input>
  <label></label>
</div>
```

Потом, когда будешь стилизовать поймешь в чем соль)

**Comment by elemeNtk0** [comment]
Сорян. Я спутал фиелдсет с легендой. Заголовок верни в `h2`. А фиелдсеты оставь)
стилизовать будет проще.

Подписи оставь как вариант 1. А еще лучше добавь обёртку для каждой пары

``` html
<div>
  <input>
  <label></label>
</div>
```

Потом, когда будешь стилизовать поймешь в чем соль)

**Comment by stan-devproject** [comment]
Ок, сделаю как ты сказал. 

Меня правда смущает не очень красивый на мой взгляд вид обертки <div></div> — так и хочется ей какой-то класс задать что-ли. :)
1. Почему именно стилизовать h2 проще, чем legend?
2. Почему ты выбрал подписи как вариант 1 — меня именно обоснование выбора интересует.

**Comment by elemeNtk0** [comment]
##### Legend / не legend

У `legend` свои "странные" стили. Если ты хочешь — оставляй легенду :) можно и так и так. Но проще было бы c `h2`. 

##### Чекбоксы & радиобатоны

Вся идея стилизации заключается в абсолютном позиционировании инпута и "фейковым" скрытием его (opacity).
А активация будет происходить по псевдоклассу `:checked` и соседнему селектору `+`. Поэтому порядок инпут+лейбл важен. Вся стилизация будет на лейбле. 

``` css
input:checked + label {
  do it
}
```

**Comment by stan-devproject** [comment]
О, благодарю, с инпутом и лейблом стало теперь понятно.

Поясни, пожалуйста, что значит странные стили у legend? Моя цель - разобраться и делать ясный осознанный выбор тегов. :)

**Comment by elemeNtk0** [comment]
ты должен отталкиваться от ситуации. В данной ситуации проще реализовать с обычным блочным тегом, чем `legend`, потому что легенда отображается [не круто](http://cssdeck.com/labs/4ayyggta)) и тебе придется исхитрятся с ней, чтобы сделать как на макете.

**Comment by elemeNtk0** [comment]
Принято
