### ISSUE TITLE
940→960

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/barbershop-id85318#10]
В барбере задай паддинги слева и справа по 10. Можешь прям у боди задать, а можешь у `.container`. 
http://joxi.ru/8An0lZ1iKXvnmO
Я забыл упомянуть про «хороший тон» верстальщика: оставлять 10 пиксельные отступы слева и справа, чтобы текст в минимальном разрешении не прижимался к краям браузера.

**Comment by stan-devproject** [comment]
Ок, сделал.
