### ISSUE TITLE
Line-height

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/barbershop-id85318#11]
Мы ведь обсудили как измерять line-height для строк текста.
Там явно видно, что 17px http://joxi.ru/BA04YgqUq9jjAy, а утебя 14.

Как сделаешь 17, сразу убавь на 2 пикселя отступ у дива, который оборачивает каждый блок (чекбокс+лейбл).

**Comment by elemeNtk0** [comment]
Ну и там проверишь уже по пиксель-перфекту. какие отступы поменять еще надо

**Comment by stan-devproject** [comment]
Ок, исправил, в других местах пока что не нашел таких проблем. Только почему убрать на 2 пикселя отступ у дива, когда логичней на 3, ведь 17-14=3px?

**Comment by stan-devproject** [comment]
И вот нашел в демонстрации как сделали сетку футера:
https://htmlacademy.ru/intensive-participant/15/resource/50#step97

То есть там первая колонка взята 320px, от нее маргин вправо 80px и сразу начинается блок с социальными иконками, который они прижали влево (то есть размер ужимается под содержимое), а блок копирайт прижали вправо с max-width: 320px; То есть здесь неограничена ширина социального блока, что чревато проблема с переполнением.

Я сделал первую колонку аналогично (320px + margin-right 80px)
Вторую колонку с социальными кнопками я тоже прижал влево, но поставил max-width: 320px;
А блоку копирайта я задал max-width: 220px, соответственно по умолчанию он ужимается под содержимое и центрируется. Ну и все по сетке.

Что скажешь?

**Comment by elemeNtk0** [comment]
Да, Согласен с тобой. Так будет лучше.
Закрываю
