### ISSUE TITLE
Catalog: добавить обёртки в основном контенте

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/barbershop-id85318#2]
В блоке `.items-section` нет пагинации. Точней она есть. но она идет после списка товаров. 
Правильно будет сделать так: обернуть список товаров + пагинацию в див «враппер», который будет отделять от фильтра. 
А сейчас тебе придётся добавлять для пагинации отдельный отступ слева,т.к. этот блок на 1м уровне с фильтром и списком товаров

**Comment by stan-devproject** [comment]
Сделал, то есть у меня есть центровщик container и есть отдельно див wrapper в верстке - правильно?

**Comment by elemeNtk0** [comment]
Враппер устоявшийся термин. я имею ввиду "обёртка" формально. Конкретно в каталоге нужен общий див для списка товаров и пагинации. Представь, что у тебя будет 15 товаров там, где должна оказаться пагинация? ) под ними или под сайдбаром слева? ;)

**Comment by elemeNtk0** [comment]
Принято
