### ISSUE TITLE
Картинки

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/barbershop-id85318#3]
На странице catalog-item.html советую вырезать по-другому картинки → чтобы не было теней.
Сейчас не могу скачать барбершоп, но вроде там тень у них сделана стилями...
Отпишись плиз, если тень растрирована с картинкой то не переделывай.

Тени, как правило, делают стилями. `box-shadow:`. Поэтому обычно вырезаем картинки без них и без рамок.

**Comment by stan-devproject** [comment]
Да, именно в этих картинках в фотошопе можно убрать эффекты, а в Avocode у меня не получилось. Хотя другие картинки Avocode экспортировал нормально.

Ок, перезагрузил с фотошопа без тени.

**Comment by elemeNtk0** [comment]
Красаучег!
