### ISSUE TITLE
Вопрос про ссылки

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/barbershop-id85318#5]
давай его мусолить будем тут.
Но советую пройти еще раз [курс](https://htmlacademy.ru/courses/66), так сказать "вспомнить". Про наследование ии каскадирование. И ты сам ответишь на свой вопрос :)

**Comment by stan-devproject** [comment]
Селектор по классу более специфичный, чем селектор по тегу - это понятно.

Но я пытался стилизовать именно a:active {} - и он у меня не работал, хотя в коде .class:active вроде не было (но была стилизация просто .active)

Вот здесь непонятно. То есть я хотел для всех ссылок задать стили, например, для a:visited {}, чтобы каждой по отдельности не задавать.

**Comment by elemeNtk0** [comment]
`:active` — стилизует только в момент нажатия.
Может ты что-то путаешь с классом `.active` ?)

**Comment by stan-devproject** [comment]
Возможно.

Вопрос в целом такой: 

Eсли я стилизую a:visited {}

А потом отдельно стилизую классы ссылок (БЕЗ :visited)
.link-1 {}
.link-2 {}

То вот к этим ссылкам .link1 и .link2 у меня будет применяться стилизация от a:visited {}

**Comment by elemeNtk0** [comment]
Думаю да. Но лучше проверь)

**Comment by stan-devproject** [comment]
Проверил, работает: http://codepen.io/anon/pen/PPqELB
