### ISSUE TITLE
Иконки

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/barbershop-id85318#6]
ты зря вырезал все иконки картинками, советую сделать спрайты. Чтобы грузить 1 картинку. Для всех иконок что будут на сайте заюзай спрайт

**Comment by stan-devproject** [comment]
Ок, подключил спрайт. Как я понял, фоновое изображение, которое повторяется, через спрайт не подключишь?

**Comment by elemeNtk0** [comment]
Да, правильно понял ) background-repeat репитит всю картинку целиком

**Comment by elemeNtk0** [comment]
Иконки.
Тут короче надо чекбоксы переделать, не должно быть никаких подгонок типа `top: -1px`. Пиксель перфектом пользуйся только в том случае, когда уже все размеры измерил, все вписал и в конце должен сверяться, не должно быть таких подгонок.

В данном случае предлагаю вырезать не крестик, а весь квадрат с крестиком и просто пустой квадрат. 
Либо постарайся выравнять правильно без всяких `top:-`px`.

**Comment by stan-devproject** [comment]
А почему не должно быть таких подгонок? Что в них плохого? Мне кажется все-таки грамотнее квадрат рисовать средствами CSS, так же более кросс-браузерно.

**Comment by elemeNtk0** [comment]
Не должно быть) У тебя должен крестик сдвигаться, а не сама рамка ))

**Comment by stan-devproject** [comment]
Просто вот в демонстрации примерно так же, как и я делают: https://htmlacademy.ru/intensive-participant/15/resource/52#step22

```
.login-form input[type="checkbox"] + label::before {
  content: "";

  position: absolute;
  top: 2px;
  left: 0;

  width: 17px;
  height: 17px;
  border: 2px solid #000;
}
```

Или ты имеешь ввиду, что именно отрицательных не должно быть, а положительные - ок?
Мне совсем не хочется делать 2px квадрат изображением...

**Comment by elemeNtk0** [comment]
вот блин намудрили-то... Ладно оставляй. раз показали. Ну обычно я стараюсь двигать иконку а не то, где иконка. Это как-то логичней.

**Comment by stan-devproject** [comment]
Ок.

**Comment by stan-devproject** [comment]
Тогда закрывай issue.
