### ISSUE TITLE
Сразу удали лишнее

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/barbershop-id85318#7]
Лишнее — атрибуты `type="text/css"` в подключаемых файлах. В HTML5 это лишнее.
Так же подключенный гугл шрифт подведи сразу к общему формату `&` → `&amp;`, одинарные кавычки сделай двойными (как во всем остальном коде)

**Comment by stan-devproject** [comment]
Вот это не понял:
Так же подключенный гугл шрифт подведи сразу к общему формату & → `&amp;`

**Comment by elemeNtk0** [comment]
ну замени символ & на `&amp;`

**Comment by stan-devproject** [comment]
Благодарю, раньше не знал, что & в ссылках — невалидный. Ок, принято.
