### ISSUE TITLE
Не к сеткам относится, но сразу помечу

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/barbershop-id85318#8]
[Первый скрин](http://joxi.ru/EA4pYE0c0XOnAb) — ссылкой должна быть здесь вся область, а то нелогично делать на `li:hover` подсветку фона. добавь паддинги для ссылки, либо сделай ее блочной. тогда тебе нижний бордер придётся делать немного "хитрее" ( через псевдо-элемент)

**Comment by elemeNtk0** [comment]
Про тег aside + main. Скорее всего они должны быть на 1м уровне. Думаю не стоит вкладывать в main еще какой-то дико семантичный "сайдбар". Скорее всего надо погуглить на этот счёт. Посмотри, что пишут тут: 
[1](http://web-standards.ru/articles/avoiding-html5-mistakes/)
[2](http://habrahabr.ru/post/214407/)
[3](http://html5book.ru/html5-semantic-elements/)
[4](http://frontender.info/the-main-element/)

**Comment by elemeNtk0** [comment]
Кнопка купить, Она у тебя должна быть абсолютно одинаковой, независимо от того, где находится. Лучше воздействовать на нее "извне", например в случае со страницей товара, эта кнопка "купить" у тебя должна просто встать в блок без какого-либо обнуления отступов.

А в случае с товарами в списке Я бы обернул и название товара и кнопку в див, у которого и проставил бы отступ слева и справа. 

Ссылке бы дал display:block., чтобы она в инспекторе правильно отображалась и точно занимала всю ширину. Картинке внутри ссылки display:block; max-width:100%;height: auto; 
Отступ у картинки бы убрал и сделал отступ у ссылки, лишний раз "не стоит выпирать блок.

**Comment by elemeNtk0** [comment]
Если `line-height` не указан в макете, то измерять его надо [так](http://joxi.ru/52aQpoWI0lkJ20)

**Comment by stan-devproject** [comment]
1. Ссылки в главном меню переделал.
2. Ок, тэг main убрал :)
3. Кнопку купить переделал таблицей с жесткими размерами ячеек. + для позиционирования в каталоге добавил еще один див item-price-positioner. Кстати, как идея, можно еще реализовать дивом (инлайн-блок) с высотой строки во всю высоту блока, и позиционировать по центру и с vertical-align: middle. Тоже должно хорошо получиться.
4. Про line-height понятно, а если есть только одна строчка текста? И надо померять расстояние от нее до границы блока?

**Comment by stan-devproject** [comment]
3.1 Со ссылкой сделал как ты сказал, только проясни значение max-width: 100%; height: auto; — как я понял, если потом контент-менеджер вставит картинку img с большими размерами в атрибутах width и height (или без этих атрибутов, но просто картинку большую, чем размер нашего блока), то наша верстка порушиться. 

Чтобы этого не случилось, мы указываем максимальный размер картинки в 100%. А зачем height: auto?

**Comment by elemeNtk0** [comment]
> А зачем height: auto?

А ты проверь ) 
Пропорции картинки надо как-то сохранять) Height могут ведь и указать в атрибутах ;)

**Comment by stan-devproject** [comment]
Понятно, благодарю.

**Comment by elemeNtk0** [comment]
Про line-height. Речь у нас изначально шла про возможное переполнение текста, следовательно несколько строк. Поэтому лайн хейт нужен адекватный, а не просто "1".

**Comment by stan-devproject** [comment]
Про line-height не понял последнего предложения твоего.

**Comment by elemeNtk0** [comment]
тьфу блин, я запутался. 
Я делаю так — измеряю лайн хейт фейково, т.е. редактирую текст и переношу часть слова на другую строку `enter`. 
После чего вручную измеряю line-height.

http://joxi.ru/xAeeoPZsVll1Ay
Вот замерил и получил 22px, нашел середину маленькой буквы и от нее 11 пикселей вверх и 11 в низ. Вот и узнали границы, от которых плясать.
Насколько я знаю — это так делается)

**Comment by stan-devproject** [comment]
Ок, благодарю.
Вот кстати ты просил часть книги, где про вертикальное выравнивание: http://css-live.ru/articles/ikf-vertikalnoe-vyravnivanie-v-stroke-chast-1-8-ya-publikaciya-cikla-tajny-css2-1%E2%80%B3.html

**Comment by stan-devproject** [comment]
Еще небольшой вопрос: я слышал, что лучше задавать жирность text-weight: 700; вместо text-weight: bold; — это так? Почему так стоит делать?

**Comment by elemeNtk0** [comment]
честно — не задавался таким вопросом) может быть bold на 1 символ больше чем 700 )

**Comment by stan-devproject** [comment]
Ок, проверь, пожалуйста, и по-закрывай issue. (я запрос на проверку из интерфейса академии уже отправил)
